name: rag

networks:
  cap-multi-compose:
    name: cap-multi-compose
  default:
    name: rag

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    
  api:
    command: ["uvicorn", "src.api:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
    container_name: rag-api
    build: .
    ports:
      - "8012:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY:-not_set}
      - DEBUG=True
    volumes:
      - ./logs:/app/logs
      - ./:/app
    depends_on:
      - qdrant
    networks:
      - cap-multi-compose
      - default
  viz:
    build: 
      context: .
      dockerfile: src/logging/viz/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api

volumes:
  qdrant_data: 