name: legit-rag
services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    
  api:
    container_name: rag-api
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--reload"]
    build: .
    ports:
      - "8012:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=documents
      - OPENAI_API_KEY=${OPEN_API_KEY:-not_set}
    volumes:
      - .:/app
    depends_on:
      - qdrant

volumes:
  qdrant_data: 